FROM python:latest

MAINTAINER Caojh
RUN /usr/local/bin/pip3 install requests
RUN /usr/local/bin/pip3 install lxml
RUN /usr/local/bin/pip3 install apscheduler
COPY ./zmz /zmz
CMD ["python3","/zmz/getzmz.py"]


