FROM centos:centos7.5.1804

MAINTAINER Caojh
RUN yum -y install python3
RUN yum -y install wget
RUN wget https://bootstrap.pypa.io/3.2/get-pip.py && python3 get-pip.py
RUN pip3 install --upgrade pip
RUN pip3 install requests
RUN pip3 install lxml
RUN pip3 install apscheduler
RUN yum -y remove wget
COPY ./zmz /zmz
ENV PYTHONIOENCODING UTF-8
CMD ["python3","/zmz/getzmz.py"]


